version: "3.3"
services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
     - '9090:9090'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml 
      - storage:/prometheus-data
  push-gateway:
    image: prom/pushgateway
    restart: always
    ports:
     - '9091:9091'
  
volumes:
  storage: {}
